language: node_js
matrix:
  include:
  - node_js: '9'
    os: osx
    script: npm run test
    addons:
      chrome: stable
      firefox: latest
    before_script:
    - export DISPLAY=:99.0
    script:
    - npm run lint
    - npm run test
    - npm run build